import type { FrameworkConfig } from "./types"

export const cxConfig: FrameworkConfig = {
  id: "cx",
  name: "Customer Experience (CX) — Modèle de maturité 8 dimensions",
  shortName: "CX",
  description: "Expérience Client — Modèle de maturité omnicanal, VoC, parcours et gouvernance CX",
  iconName: "Star",
  accentColor: "orange",
  maxScore: 5,
  globalScoreMock: 1.59,
  dimensions: [
    {
      id: "ecoute",
      label: "Écoute client et données",
      radarLabel: "Écoute client",
      color: "#f97316",
      items: [
        { id: "d1.1", label: "D1.1 Système VoC (Voice of Customer) multimodal déployé", score: 1 },
        { id: "d1.2", label: "D1.2 Centralisation des données client dans un CRM unifié", score: 2 },
        { id: "d1.3", label: "D1.3 Personas B2B et B2C formalisés et mis à jour", score: 2 },
        { id: "d1.4", label: "D1.4 Mesure régulière du NPS par segment et touchpoint", score: 1 },
        { id: "d1.5", label: "D1.5 Suivi du CSAT par canal et étape du parcours", score: 2 },
        { id: "d1.6", label: "D1.6 Mesure du CES (Customer Effort Score) par interaction", score: 1 },
        { id: "d1.7", label: "D1.7 Études qualitatives (focus groups, entretiens) planifiées", score: 1 },
      ],
    },
    {
      id: "parcours",
      label: "Cartographie du parcours client",
      radarLabel: "Parcours",
      color: "#fb923c",
      items: [
        { id: "d2.1", label: "D2.1 Parcours client (journey map) formalisé par persona", score: 2 },
        { id: "d2.2", label: "D2.2 Points de contact critiques identifiés et priorisés", score: 2 },
        { id: "d2.3", label: "D2.3 Points de friction et irritants documentés", score: 2 },
        { id: "d2.4", label: "D2.4 Parcours digital optimisé (UX, conversion, abandon)", score: 1 },
        { id: "d2.5", label: "D2.5 Parcours physique standardisé et évalué", score: 2 },
        { id: "d2.6", label: "D2.6 Continuité cross-canal assurée (pas de rupture d'info)", score: 1 },
        { id: "d2.7", label: "D2.7 Parcours revu après chaque changement majeur", score: 2 },
      ],
    },
    {
      id: "culture",
      label: "Culture client et engagement interne",
      radarLabel: "Culture CX",
      color: "#f59e0b",
      items: [
        { id: "d3.1", label: "D3.1 Leadership DG sur la vision CX (Chief Customer Officer)", score: 1 },
        { id: "d3.2", label: "D3.2 Objectifs CX intégrés dans les évaluations de performance", score: 2 },
        { id: "d3.3", label: "D3.3 Formation des équipes à l'empathie et la culture client", score: 1 },
        { id: "d3.4", label: "D3.4 Rituels internes de partage des verbatims clients", score: 1 },
        { id: "d3.5", label: "D3.5 Mesure de la corrélation EX / CX (expérience employé)", score: 2 },
        { id: "d3.6", label: "D3.6 Comité CX transversal (Marketing, Commercial, Ops, Digital)", score: 1 },
        { id: "d3.7", label: "D3.7 Diffusion des résultats clients à toutes les équipes", score: 1 },
      ],
    },
    {
      id: "relation",
      label: "Relation client et fidélisation",
      radarLabel: "Relation",
      color: "#ea580c",
      items: [
        { id: "d4.1", label: "D4.1 Gestion des réclamations formalisée (processus IDEI)", score: 2 },
        { id: "d4.2", label: "D4.2 SLA définis et respectés par canal de contact", score: 2 },
        { id: "d4.3", label: "D4.3 Personnalisation des interactions et des offres", score: 1 },
        { id: "d4.4", label: "D4.4 Programme de fidélité structuré (B2B/B2C adapté)", score: 2 },
        { id: "d4.5", label: "D4.5 Suivi post-achat systématique", score: 2 },
        { id: "d4.6", label: "D4.6 Détection du risque de churn et actions de rétention", score: 1 },
        { id: "d4.7", label: "D4.7 Programme d'ambassadeurs et de co-création clients", score: 2 },
      ],
    },
    {
      id: "omnicanal",
      label: "Omnicanalité et cohérence des canaux",
      radarLabel: "Omnicanal",
      color: "#c2410c",
      items: [
        { id: "d5.1", label: "D5.1 Inventaire exhaustif des canaux de contact actifs", score: 2 },
        { id: "d5.2", label: "D5.2 Cohérence de l'expérience sur l'ensemble des canaux", score: 2 },
        { id: "d5.3", label: "D5.3 Passage d'un canal à l'autre sans répéter les informations", score: 1 },
        { id: "d5.4", label: "D5.4 Self-service disponible 24/7 (FAQ, chatbot, espace client)", score: 2 },
        { id: "d5.5", label: "D5.5 Surveillance et engagement sur les réseaux sociaux", score: 2 },
        { id: "d5.6", label: "D5.6 Performance des canaux digitaux B2B mesurée avec KPI", score: 1 },
        { id: "d5.7", label: "D5.7 Analyse sémantique des verbatims multicanaux", score: 2 },
      ],
    },
    {
      id: "mesure",
      label: "Pilotage et mesure de l'expérience",
      radarLabel: "Pilotage",
      color: "#9a3412",
      items: [
        { id: "d6.1", label: "D6.1 Dashboard CX avec KPI en temps réel (NPS, CSAT, CES)", score: 1 },
        { id: "d6.2", label: "D6.2 Lien mesuré entre CX et résultats financiers (churn)", score: 2 },
        { id: "d6.3", label: "D6.3 Revues CX cross-fonctionnelles mensuelles", score: 1 },
        { id: "d6.4", label: "D6.4 Analyse des verbatims (sémantique, IA textuelle)", score: 2 },
        { id: "d6.5", label: "D6.5 Benchmarking concurrentiel régulier (NPS sectoriel)", score: 1 },
        { id: "d6.6", label: "D6.6 Processus Close-the-Loop (contact détracteurs < 48h)", score: 1 },
        { id: "d6.7", label: "D6.7 Calcul et suivi du ROX (Return on eXperience)", score: 2 },
      ],
    },
    {
      id: "personnalisation",
      label: "Personnalisation et innovation CX",
      radarLabel: "Innovation",
      color: "#7c3aed",
      items: [
        { id: "d7.1", label: "D7.1 Segmentation fine (comportements, valeur, cycles de vie)", score: 1 },
        { id: "d7.2", label: "D7.2 Personnalisation temps réel sur le digital (IA, reco)", score: 1 },
        { id: "d7.3", label: "D7.3 Moments WOW délibérément conçus aux étapes clés", score: 1 },
        { id: "d7.4", label: "D7.4 Innovation CX structurée (Design Thinking, labs CX)", score: 2 },
        { id: "d7.5", label: "D7.5 Exploration nouvelles technologies (IA conv., AR/VR)", score: 1 },
        { id: "d7.6", label: "D7.6 Co-création clients (bêta-testeurs, panels, communautés)", score: 1 },
        { id: "d7.7", label: "D7.7 Mesure délibérée de l'expérience émotionnelle positive", score: 2 },
      ],
    },
    {
      id: "gouvernance",
      label: "Gouvernance et organisation CX",
      radarLabel: "Gouvernance",
      color: "#6366f1",
      items: [
        { id: "d8.1", label: "D8.1 Équipe CX dédiée avec budget propre", score: 2 },
        { id: "d8.2", label: "D8.2 Programme CX formalisé avec objectifs et jalons", score: 2 },
        { id: "d8.3", label: "D8.3 Stratégie CX alignée avec la stratégie d'entreprise", score: 1 },
        { id: "d8.4", label: "D8.4 Priorisation des investissements CX par ROX", score: 2 },
        { id: "d8.5", label: "D8.5 Comité CX transversal régulier avec toutes les fonctions", score: 2 },
        { id: "d8.6", label: "D8.6 Identification/amélioration des processus internes bloquants", score: 1 },
        { id: "d8.7", label: "D8.7 Évaluation périodique de la maturité CX et plan progrès", score: 2 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et gouvernance CX",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe CX (Chief Customer Officer, pilotes métiers, digital)",
        "Réaliser le diagnostic de maturité CX sur les 8 dimensions",
        "Formaliser la vision CX alignée sur la stratégie d'entreprise",
        "Obtenir l'engagement de la direction et allouer le budget CX",
        "Définir les KPI prioritaires (NPS, CSAT, CES, taux de churn)",
      ],
      milestone: "Rapport de maturité CX validé, gouvernance et vision CX approuvées par la DG",
    },
    {
      phase: 2,
      title: "Phase 2 — Écoute client et VoC",
      duration: "3 mois",
      actions: [
        "Déployer le programme VoC multimodal (enquêtes, verbatims, NPS/CSAT/CES)",
        "Mettre en place ou consolider le CRM unifié pour toutes les données client",
        "Formaliser les personas B2B et B2C par segment de clientèle",
        "Créer le dashboard CX avec indicateurs en temps réel",
        "Déployer le processus Close-the-Loop (traitement des détracteurs < 48h)",
      ],
      milestone: "Programme VoC opérationnel, CRM déployé, premier NPS consolidé par segment",
    },
    {
      phase: 3,
      title: "Phase 3 — Parcours client et culture interne",
      duration: "4 mois",
      actions: [
        "Cartographier les parcours clients (journey maps) par persona et canal",
        "Identifier et prioriser les points de friction à fort impact",
        "Lancer le programme de formation à la culture client (empathie, CX)",
        "Créer les rituels internes de partage des verbatims clients",
        "Mettre en place le comité CX transversal mensuel",
      ],
      milestone: "Journey maps validées, plan d'amélioration des irritants, culture CX en déploiement",
    },
    {
      phase: 4,
      title: "Phase 4 — Omnicanal et personnalisation",
      duration: "4 mois",
      actions: [
        "Garantir la cohérence de l'expérience sur l'ensemble des canaux (phygital)",
        "Déployer le self-service 24/7 (chatbot, FAQ intelligente, espace client)",
        "Lancer la segmentation avancée et les premiers cas de personnalisation",
        "Mettre en place le programme de fidélité et de rétention clients",
        "Déployer l'analyse sémantique des verbatims multicanaux",
      ],
      milestone: "Cohérence omnicanale assurée, self-service opérationnel, personnalisation active",
    },
    {
      phase: 5,
      title: "Phase 5 — Innovation CX et ROX",
      duration: "Continu",
      actions: [
        "Lancer le lab CX (Design Thinking, co-création, bêta-tests clients)",
        "Explorer les technologies d'innovation (IA conversationnelle, AR/VR)",
        "Calculer et piloter le ROX (Return on eXperience) comme KPI stratégique",
        "Mesurer et améliorer en continu la maturité CX globale",
      ],
      milestone: "Lab CX opérationnel, ROX mesuré et diffusé, maturité CX ≥ 3/5",
    },
  ],
}
