import type { FrameworkConfig } from "./types"

export const esgConfig: FrameworkConfig = {
  id: "esg",
  name: "ESG / CSRD / GRI — Rapport de durabilité",
  shortName: "ESG/CSRD",
  description: "Stratégie ESG, reporting CSRD/ESRS et conformité GRI — Double matérialité et piliers E, S, G",
  iconName: "Globe",
  accentColor: "green",
  maxScore: 5,
  globalScoreMock: 1.89,
  dimensions: [
    {
      id: "e1",
      label: "E1 — Changement climatique",
      radarLabel: "Climat (E1)",
      color: "#16a34a",
      items: [
        { id: "e1.1", label: "E1.1 Gouvernance climatique — supervision par la direction", score: 2 },
        { id: "e1.2", label: "E1.2 Stratégie bas-carbone — objectifs Net Zero (SBTi)", score: 2 },
        { id: "e1.3", label: "E1.3 Émissions GES Scope 1 — combustion directe et procédés", score: 2 },
        { id: "e1.4", label: "E1.4 Émissions GES Scope 2 — énergie achetée (électricité)", score: 2 },
        { id: "e1.5", label: "E1.5 Émissions GES Scope 3 — chaîne de valeur (15 catégories)", score: 1 },
        { id: "e1.6", label: "E1.6 Intensité carbone — tCO2e/CA ou tCO2e/unité produite", score: 2 },
        { id: "e1.7", label: "E1.7 Plan de réduction avec jalons et budget carbone", score: 1 },
        { id: "e1.8", label: "E1.8 Analyse risques physiques et de transition (TCFD)", score: 2 },
      ],
    },
    {
      id: "e_autres",
      label: "E2-E5 — Pollution, eau, biodiversité, économie circulaire",
      radarLabel: "Env. (E2-E5)",
      color: "#22c55e",
      items: [
        { id: "e2.1", label: "E2.1 Émissions polluants atmosphériques (NOx, SOx, COV)", score: 2 },
        { id: "e2.2", label: "E2.2 Rejets polluants dans l'eau (DBO, métaux lourds)", score: 1 },
        { id: "e3.1", label: "E3.1 Consommation totale d'eau et prélèvements par source", score: 2 },
        { id: "e3.3", label: "E3.3 Eau recyclée/réutilisée — ratio de circularité hydrique", score: 2 },
        { id: "e4.1", label: "E4.1 Impacts biodiversité — cartographie des sites sensibles", score: 2 },
        { id: "e5.1", label: "E5.1 Consommation matières premières (renouv./non-renouv.)", score: 1 },
        { id: "e5.3", label: "E5.3 Production totale de déchets par catégorie et filière", score: 2 },
        { id: "e5.4", label: "E5.4 Taux de valorisation déchets (réemploi, recyclage)", score: 2 },
      ],
    },
    {
      id: "s1",
      label: "S1 — Effectifs propres",
      radarLabel: "Effectifs (S1)",
      color: "#0ea5e9",
      items: [
        { id: "s1.1", label: "S1.1 Effectif total — CDI/CDD, genre, âge, temps plein/partiel", score: 3 },
        { id: "s1.2", label: "S1.2 Taux de turnover et taux d'embauche/départ", score: 2 },
        { id: "s1.3", label: "S1.3 Égalité de rémunération H/F (écart ajusté et brut)", score: 2 },
        { id: "s1.4", label: "S1.4 Taux de femmes dans les postes de direction", score: 2 },
        { id: "s1.5", label: "S1.5 Formation — heures moyennes/collaborateur, budget/CA", score: 2 },
        { id: "s1.6", label: "S1.6 Santé-sécurité — taux de fréquence (TF) et gravité (TG)", score: 2 },
        { id: "s1.7", label: "S1.7 Maladies professionnelles — taux et types déclarés", score: 2 },
        { id: "s1.9", label: "S1.9 Bien-être au travail — indice d'engagement, absentéisme", score: 1 },
      ],
    },
    {
      id: "s_autres",
      label: "S2-S4 — Chaîne de valeur, communautés, consommateurs",
      radarLabel: "Social (S2-S4)",
      color: "#38bdf8",
      items: [
        { id: "s2.1", label: "S2.1 Identification risques droits humains dans la chaîne valeur", score: 1 },
        { id: "s2.2", label: "S2.2 Audit social fournisseurs (EcoVadis, SEDEX)", score: 2 },
        { id: "s3.1", label: "S3.1 Dialogue communautés locales — consultation et recours", score: 2 },
        { id: "s4.1", label: "S4.1 Satisfaction client et mécanismes de remontée réclamations", score: 2 },
        { id: "s4.2", label: "S4.2 Santé-sécurité produits — conformité, rappels, incidents", score: 2 },
      ],
    },
    {
      id: "g1",
      label: "G1 — Conduite des affaires",
      radarLabel: "Gouvernance",
      color: "#8b5cf6",
      items: [
        { id: "g1.1", label: "G1.1 Composition et indépendance du conseil d'administration", score: 2 },
        { id: "g1.2", label: "G1.2 Diversité du conseil — genre, âge, compétences, nationalité", score: 2 },
        { id: "g1.3", label: "G1.3 Rémunération dirigeants — politique, ratio CEO/médian", score: 2 },
        { id: "g1.4", label: "G1.4 Code d'éthique et politique anti-corruption (SAPIN II)", score: 2 },
        { id: "g1.5", label: "G1.5 Dispositif anti-corruption — cartographie, formation", score: 1 },
        { id: "g1.6", label: "G1.6 Programme de conformité réglementaire (compliance)", score: 2 },
        { id: "g1.7", label: "G1.7 Protection lanceurs d'alerte — canal sécurisé confidentiel", score: 1 },
        { id: "g1.8", label: "G1.8 Cybersécurité et RGPD — politique, incidents, contrôles", score: 2 },
      ],
    },
    {
      id: "g2",
      label: "G2 — Stratégie et rapport ESG",
      radarLabel: "Stratégie ESG",
      color: "#a78bfa",
      items: [
        { id: "g2.1", label: "G2.1 Double matérialité — analyse impact/financière et résultats", score: 2 },
        { id: "g2.2", label: "G2.2 Stratégie ESG intégrée au corporate, objectifs 2030", score: 2 },
        { id: "g2.3", label: "G2.3 Rapport durabilité conforme CSRD/ESRS, vérification tierce", score: 1 },
        { id: "g2.4", label: "G2.4 Mécanismes de recours accessibles aux parties prenantes", score: 2 },
      ],
    },
    {
      id: "csrd",
      label: "Conformité CSRD et reporting",
      radarLabel: "CSRD/GRI",
      color: "#10b981",
      items: [
        { id: "csrd.1", label: "CSRD.1 Identification des ESRS après double matérialité", score: 2 },
        { id: "csrd.2", label: "CSRD.2 Collecte données ESG structurée, traçable et auditée", score: 1 },
        { id: "csrd.3", label: "CSRD.3 Système de gestion données ESG (Excel avancé ou logiciel)", score: 2 },
        { id: "csrd.4", label: "CSRD.4 Assurance tierce partie (OTI) — portée limitée/raisonnable", score: 2 },
        { id: "csrd.5", label: "CSRD.5 Étiquetage XBRL pour dépôt électronique (ESEF européen)", score: 1 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Fondations gouvernance ESG",
      duration: "3 mois",
      actions: [
        "Constituer l'équipe ESG (Directeur Durabilité, Finance, RH, Opérations)",
        "Définir la politique ESG et obtenir l'approbation du conseil d'administration",
        "Réaliser l'analyse de double matérialité (impacts, risques, opportunités)",
        "Identifier les ESRS applicables et les données à collecter",
        "Mettre en place la gouvernance ESG (comité, reporting, indicateurs clés)",
      ],
      milestone: "Politique ESG approuvée par le CA, analyse de double matérialité finalisée",
    },
    {
      phase: 2,
      title: "Phase 2 — Diagnostic et baseline ESG",
      duration: "3 mois",
      actions: [
        "Réaliser l'inventaire GES Scope 1, 2 et 3 (bilan carbone)",
        "Collecter les données sociales de référence (S1 : effectifs, TF, formation)",
        "Auditer la gouvernance et les pratiques anti-corruption existantes",
        "Établir les valeurs de référence (baseline) pour tous les KPI ESG",
        "Identifier les lacunes de données et mettre en place les outils de collecte",
      ],
      milestone: "Baseline ESG établie, lacunes identifiées, système de collecte opérationnel",
    },
    {
      phase: 3,
      title: "Phase 3 — Déploiement Environnement",
      duration: "7 mois",
      actions: [
        "Définir les objectifs de réduction GES alignés sur SBTi (1,5°C)",
        "Déployer le plan d'efficacité énergétique et de transition bas-carbone",
        "Mettre en place les programmes eau, déchets et biodiversité",
        "Engager les fournisseurs clés sur les critères ESG (Scope 3)",
        "Suivre les KPI environnementaux et publier les premiers résultats",
      ],
      milestone: "Objectifs GES validés SBTi, plan transition déployé, KPI environnementaux actifs",
    },
    {
      phase: 4,
      title: "Phase 4 — Déploiement Social et Gouvernance",
      duration: "8 mois",
      actions: [
        "Déployer le plan d'action égalité F/H et diversité (Index Égalité Professionnelle)",
        "Renforcer les dispositifs santé-sécurité et bien-être au travail",
        "Mettre en place le programme anti-corruption conforme SAPIN II",
        "Déployer le canal d'alerte et la protection des lanceurs d'alerte",
        "Renforcer l'audit social de la chaîne de valeur fournisseurs",
      ],
      milestone: "Plan D&I opérationnel, SAPIN II conforme, canal alerte déployé",
    },
    {
      phase: 5,
      title: "Phase 5 — Rapport CSRD et assurance OTI",
      duration: "8 mois",
      actions: [
        "Rédiger le rapport de durabilité conforme aux ESRS applicables",
        "Préparer l'assurance à portée limitée par un OTI accrédité",
        "Préparer le format XBRL pour le dépôt électronique ESEF",
        "Communiquer les résultats ESG aux parties prenantes (investisseurs, clients)",
      ],
      milestone: "Rapport de durabilité CSRD publié, assurance OTI obtenue, dépôt XBRL réalisé",
    },
  ],
}
