import type { FrameworkConfig } from "./types"

export const fsscConfig: FrameworkConfig = {
  id: "fssc",
  name: "FSSC 22000 Version 6 — Sécurité Alimentaire",
  shortName: "FSSC 22000",
  description: "Système de Management de la Sécurité Alimentaire — Certification FSSC 22000 Version 6",
  iconName: "UtensilsCrossed",
  accentColor: "teal",
  maxScore: 5,
  globalScoreMock: 1.87,
  dimensions: [
    {
      id: "hls",
      label: "Chapitres HLS ISO 22000 (4-10)",
      radarLabel: "HLS (4-10)",
      color: "#14b8a6",
      items: [
        { id: "hls.4", label: "4. Contexte — parties intéressées, périmètre SMSA, chaîne alim.", score: 2 },
        { id: "hls.5", label: "5. Leadership — engagement DG, politique SA, équipe HACCP", score: 2 },
        { id: "hls.6", label: "6. Planification — risques/opportunités SMSA, objectifs SA", score: 2 },
        { id: "hls.7", label: "7. Support — ressources, compétences, communication, docs SMSA", score: 2 },
        { id: "hls.8.1", label: "8.1 Planification opérationnelle — maîtrise procédés et sous-trt.", score: 2 },
        { id: "hls.8.2", label: "8.2 Programmes Prérequis (PRP) — conditions de base production", score: 1 },
        { id: "hls.9", label: "9. Évaluation des performances — surveillance, audit, revue DG", score: 1 },
        { id: "hls.10", label: "10. Amélioration — NC, CAPA, amélioration continue du SMSA", score: 2 },
      ],
    },
    {
      id: "haccp",
      label: "Analyse des dangers et plan HACCP",
      radarLabel: "HACCP",
      color: "#0d9488",
      items: [
        { id: "haccp.8.5.1", label: "8.5.1 Analyse dangers — produits, ingrédients, matériaux contact", score: 2 },
        { id: "haccp.8.5.2", label: "8.5.2 Description produits — fiches, usages, populations vulnérables", score: 3 },
        { id: "haccp.8.5.3", label: "8.5.3 Diagrammes de flux — étapes, vérification sur site", score: 2 },
        { id: "haccp.8.5.4", label: "8.5.4 Identification dangers, évaluation, sélection mesures maîtrise", score: 2 },
        { id: "haccp.8.6", label: "8.6 Plan HACCP — CCP, limites critiques, surveillance, CAPA", score: 1 },
        { id: "haccp.8.7", label: "8.7 Mise à jour informations préliminaires et plans PRP/HACCP", score: 2 },
        { id: "haccp.8.8", label: "8.8 Validation mesures de maîtrise (CCP et PRPo)", score: 2 },
        { id: "haccp.8.9", label: "8.9 Maîtrise NC produits — retrait, rappel, libération produits", score: 1 },
      ],
    },
    {
      id: "prp",
      label: "Programmes Prérequis (PRP) — ISO/TS 22002-x",
      radarLabel: "PRP",
      color: "#2dd4bf",
      items: [
        { id: "prp.1", label: "PRP 1 Construction et agencement bâtiments (nettoyage, maintenance)", score: 2 },
        { id: "prp.2", label: "PRP 2 Fourniture en air, eau, énergie et autres utilités", score: 2 },
        { id: "prp.3", label: "PRP 3 Gestion des déchets et des effluents", score: 2 },
        { id: "prp.4", label: "PRP 4 Équipements — aptitude et accès nettoyage/désinfection", score: 2 },
        { id: "prp.5", label: "PRP 5 Gestion matières achetées (fournisseurs, specs, réception)", score: 2 },
        { id: "prp.6", label: "PRP 6 Maîtrise contamination croisée — allergènes, corps étrangers", score: 1 },
        { id: "prp.7", label: "PRP 7 Nettoyage, désinfection et lutte contre les nuisibles", score: 2 },
        { id: "prp.8", label: "PRP 8 Hygiène des personnes — santé, tenues, comportements", score: 2 },
      ],
    },
    {
      id: "traceabilite",
      label: "Traçabilité et gestion des urgences",
      radarLabel: "Traçabilité",
      color: "#5eead4",
      items: [
        { id: "trac.8.3", label: "8.3 Traçabilité — lots, ingrédients, emballages, flux amont/aval", score: 3 },
        { id: "trac.8.4.1", label: "8.4.1 Préparation urgences alimentaires — rappels, retraits, crises", score: 2 },
        { id: "trac.8.4.2", label: "8.4.2 Gestion urgences — plans de crise, exercices, REX", score: 2 },
        { id: "trac.9.1", label: "9.1 Vérification et validation du système de traçabilité", score: 2 },
        { id: "trac.dur", label: "FSSC Durabilité — critères ESG intégrés dans la stratégie SMSA", score: 2 },
      ],
    },
    {
      id: "fssc_add",
      label: "Exigences additionnelles FSSC 22000 v6",
      radarLabel: "Exig. FSSC v6",
      color: "#99f6e4",
      items: [
        { id: "add.1", label: "ADD 1 Food Defense — vulnérabilité aux actes malveillants", score: 1 },
        { id: "add.2", label: "ADD 2 Food Fraud — vulnérabilité à la fraude alimentaire", score: 2 },
        { id: "add.3", label: "ADD 3 Culture sécurité alimentaire — évaluation et plan progrès", score: 1 },
        { id: "add.4", label: "ADD 4 Surveillance environnementale — prélèvements, analyses micro", score: 2 },
        { id: "add.5", label: "ADD 5 Gestion allergènes — prévention contamination, étiquetage", score: 1 },
        { id: "add.6", label: "ADD 6 Transport et livraison — maîtrise conditions pendant transport", score: 2 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et périmètre SMSA",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe HACCP et désigner le responsable SMSA",
        "Réaliser le diagnostic de maturité FSSC 22000 v6 par dimension",
        "Définir le périmètre du SMSA (produits, sites, chaîne alimentaire)",
        "Identifier les parties intéressées et leurs exigences légales et clients",
        "Obtenir l'engagement de la direction générale et allouer les ressources",
      ],
      milestone: "Rapport de diagnostic validé, périmètre SMSA approuvé, équipe HACCP constituée",
    },
    {
      phase: 2,
      title: "Phase 2 — PRPs et formation équipe HACCP",
      duration: "3 mois",
      actions: [
        "Évaluer et mettre à niveau les Programmes Prérequis (PRP) selon ISO/TS 22002",
        "Former l'équipe HACCP aux principes Codex et aux exigences FSSC 22000 v6",
        "Rédiger les procédures PRP et les instructions de travail associées",
        "Mettre en place le programme de nettoyage/désinfection et lutte nuisibles",
        "Déployer les exigences de Food Defense et Food Fraud (ADD 1 et ADD 2)",
      ],
      milestone: "PRP conformes ISO/TS 22002, équipe HACCP formée, food defense évaluée",
    },
    {
      phase: 3,
      title: "Phase 3 — Analyse des dangers et plan HACCP",
      duration: "4 mois",
      actions: [
        "Réaliser l'analyse complète des dangers (biologiques, chimiques, physiques)",
        "Identifier les CCP et PRPo, définir les limites critiques et la surveillance",
        "Rédiger le plan HACCP et les fiches produits avec populations vulnérables",
        "Établir les procédures de traçabilité, retrait et rappel de produits",
        "Mettre en place le programme de surveillance environnementale (ADD 4)",
      ],
      milestone: "Plan HACCP validé, traçabilité opérationnelle, exercice de rappel réalisé",
    },
    {
      phase: 4,
      title: "Phase 4 — Audit interne et revue de direction",
      duration: "2 mois",
      actions: [
        "Réaliser le premier audit interne SMSA complet (HLS + HACCP + PRP + ADD)",
        "Analyser les indicateurs de performance sécurité alimentaire",
        "Conduire la revue de direction SMSA (résultats, ressources, objectifs SA)",
        "Traiter toutes les non-conformités et mettre à jour le plan CAPA",
        "Effectuer un exercice de rappel test pour valider la procédure",
      ],
      milestone: "Rapport d'audit interne, revue de direction documentée, CAPA finalisé",
    },
    {
      phase: 5,
      title: "Phase 5 — Certification FSSC 22000 v6",
      duration: "3 mois",
      actions: [
        "Préparer le dossier de certification et sélectionner l'organisme certificateur",
        "Accompagner l'audit de certification Étape 1 (revue documentaire SMSA)",
        "Accompagner l'audit de certification Étape 2 (audit terrain complet)",
        "Traiter les non-conformités relevées par l'auditeur de certification",
        "Obtenir le certificat FSSC 22000 v6 et planifier les audits de surveillance",
      ],
      milestone: "Certificat FSSC 22000 Version 6 obtenu, plan de surveillance annuel établi",
    },
  ],
}
