import type { FrameworkConfig } from "./types"

export const iso37001Config: FrameworkConfig = {
  id: "iso37001",
  name: "ISO 37001:2016 — SMAC Anti-Corruption (SAPIN II)",
  shortName: "ISO 37001",
  description: "Système de Management Anti-Corruption — Certification ISO 37001 et conformité Loi SAPIN II",
  iconName: "Scale",
  accentColor: "red",
  maxScore: 5,
  globalScoreMock: 1.62,
  dimensions: [
    {
      id: "hls",
      label: "Chapitres HLS ISO 37001 (4-10)",
      radarLabel: "HLS (4-10)",
      color: "#ef4444",
      items: [
        { id: "hls.4.1", label: "4.1 Comprendre l'organisme et son contexte de corruption", score: 2 },
        { id: "hls.4.5", label: "4.5 Évaluation risques corruption — cartographie initiale", score: 2 },
        { id: "hls.5.1", label: "5.1 Engagement DG et conseil d'administration (gouvernance)", score: 2 },
        { id: "hls.5.2", label: "5.2 Politique anti-corruption — contenu, diffusion, révision", score: 1 },
        { id: "hls.5.3", label: "5.3 Compliance Officer (DAFCO) — indépendance, ressources", score: 1 },
        { id: "hls.6.1", label: "6.1 Cartographie des risques — identification, analyse, priorisation", score: 2 },
        { id: "hls.6.2", label: "6.2 Évaluation tiers (due diligence) — fournisseurs, agents, JV", score: 1 },
        { id: "hls.7.3", label: "7.3 Sensibilisation — code de conduite, formations, e-learning", score: 2 },
        { id: "hls.9.4", label: "9.4 Dispositif d'alerte — canal sécurisé, anti-représailles", score: 2 },
        { id: "hls.10.2", label: "10.2 Amélioration continue — REX incidents, veille SAPIN II/FCPA", score: 1 },
      ],
    },
    {
      id: "a_org",
      label: "Contrôles organisationnels (Annexe A — A.1–A.6)",
      radarLabel: "Org. (Annexe A)",
      color: "#dc2626",
      items: [
        { id: "a.1", label: "A.1 Engagement gouvernance — approbation formelle du SMAC", score: 2 },
        { id: "a.2", label: "A.2 Supervision SMAC par la direction — reporting, métriques", score: 2 },
        { id: "a.3", label: "A.3 Compliance Officer — nomination, indépendance, accès, ressources", score: 1 },
        { id: "a.4", label: "A.4 Contrôle direction — revue annuelle SMAC, reporting intégré", score: 2 },
        { id: "a.5", label: "A.5 Évaluation risque corruption — processus documenté, mise à jour", score: 1 },
        { id: "a.6", label: "A.6 Due diligence anti-corruption — classification tiers, décision doc.", score: 2 },
      ],
    },
    {
      id: "a_finance",
      label: "Contrôles financiers (Annexe A — A.7–A.9)",
      radarLabel: "Contrôles fin.",
      color: "#b91c1c",
      items: [
        { id: "a.7", label: "A.7 Contrôles financiers — séparation tâches (SoD), doubles approbations", score: 2 },
        { id: "a.8.3", label: "8.3 Transactions sensibles — validation, audit des transactions à risque", score: 1 },
        { id: "a.8.4", label: "8.4 Cadeaux, invitations — politique, seuils, registre, approbation", score: 1 },
        { id: "a.8.5", label: "8.5 Contributions politiques et mécénat — prohibition/encadrement", score: 2 },
        { id: "a.8.8", label: "8.8 Recrutement intermédiaires — procédures validation anti-corruption", score: 2 },
      ],
    },
    {
      id: "a_non_fin",
      label: "Contrôles non-financiers (Annexe A — A.10–A.12)",
      radarLabel: "Contrôles autres",
      color: "#991b1b",
      items: [
        { id: "a.10", label: "A.10 Programme formation AC — formations ciblées selon le risque", score: 1 },
        { id: "a.11", label: "A.11 Dénonciation et protection des lanceurs d'alerte", score: 2 },
        { id: "a.12", label: "A.12 Engagement partenaires — clauses contractuelles anti-corruption", score: 2 },
        { id: "a.8.9", label: "8.9 Acquisitions et JV — due diligence pré-acquisition, post-closing", score: 1 },
        { id: "a.8.10", label: "8.10 Marchés publics — prévention conflits d'intérêts", score: 2 },
        { id: "a.9.2", label: "9.2 Audit interne SMAC — indépendance, programme risques, rapport DAFCO", score: 2 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et cartographie des risques",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe projet SMAC (DAFCO, DG, DAF, RH, Achats, Juridique)",
        "Réaliser le diagnostic de maturité ISO 37001 et SAPIN II par dimension",
        "Cartographier les risques de corruption par processus, secteur et zone géo",
        "Identifier les tiers à risque (fournisseurs, agents, intermédiaires, JV)",
        "Obtenir l'engagement formel du conseil d'administration",
      ],
      milestone: "Rapport de diagnostic validé, cartographie des risques approuvée par le CA",
    },
    {
      phase: 2,
      title: "Phase 2 — Politique AC, code de conduite et formation",
      duration: "3 mois",
      actions: [
        "Rédiger et diffuser la politique anti-corruption et le code de conduite",
        "Nommer le Compliance Officer (DAFCO) avec indépendance et ressources",
        "Déployer le programme de formation obligatoire anti-corruption (e-learning)",
        "Mettre en place la politique cadeaux/invitations avec registre et seuils",
        "Communiquer les engagements AC aux parties prenantes internes et externes",
      ],
      milestone: "Politique AC publiée, DAFCO nommé, formation AC lancée pour tous les salariés",
    },
    {
      phase: 3,
      title: "Phase 3 — Contrôles opérationnels et due diligence tiers",
      duration: "4 mois",
      actions: [
        "Déployer la procédure de due diligence anti-corruption sur les tiers à risque",
        "Mettre en place les contrôles financiers (SoD, double approbation, audit)",
        "Intégrer les clauses anti-corruption dans les contrats fournisseurs et partenaires",
        "Déployer les procédures de contrôle des marchés publics et conflits d'intérêts",
        "Mettre en place le registre des déclarations d'intérêts",
      ],
      milestone: "Due diligence opérationnelle, contrôles financiers déployés, clauses AC en contrats",
    },
    {
      phase: 4,
      title: "Phase 4 — Canal d'alerte et audit interne SMAC",
      duration: "3 mois",
      actions: [
        "Déployer le dispositif d'alerte professionnelle sécurisé et confidentiel",
        "Mettre en place la protection des lanceurs d'alerte et la procédure de traitement",
        "Réaliser le premier audit interne SMAC (basé sur les risques, rapport au CA)",
        "Conduire la revue de direction SMAC et traiter les non-conformités",
        "Tester et valider le dispositif d'alerte avec un exercice simulé",
      ],
      milestone: "Canal d'alerte opérationnel, audit interne SMAC réalisé, revue direction documentée",
    },
    {
      phase: 5,
      title: "Phase 5 — Certification ISO 37001 et conformité SAPIN II",
      duration: "3 mois",
      actions: [
        "Préparer le dossier de certification ISO 37001 et sélectionner l'OC accrédité",
        "Accompagner l'audit de certification Étape 1 (revue documentaire SMAC)",
        "Accompagner l'audit de certification Étape 2 (audit terrain complet)",
        "Produire le rapport de conformité SAPIN II pour l'AFA (Agence Française AC)",
      ],
      milestone: "Certificat ISO 37001:2016 obtenu, conformité SAPIN II démontrée auprès de l'AFA",
    },
  ],
}
