import type { FrameworkConfig } from "./types"

export const kmConfig: FrameworkConfig = {
  id: "km",
  name: "Knowledge Management — Modèle de maturité KM",
  shortName: "KM",
  description: "Gestion des connaissances — Modèle de maturité organisationnelle 6 dimensions",
  iconName: "BookOpen",
  accentColor: "amber",
  maxScore: 4,
  globalScoreMock: 1.86,
  dimensions: [
    {
      id: "socialisation",
      label: "Espaces de discussion et socialisation",
      radarLabel: "Socialisation",
      color: "#f59e0b",
      items: [
        { id: "1.1", label: "Réunions régulières de partage d'expériences (REX)", score: 2 },
        { id: "1.2", label: "Messagerie interne pour le partage de connaissances", score: 2 },
        { id: "1.3", label: "Mailing lists thématiques par domaine d'expertise", score: 1 },
        { id: "1.4", label: "Forums de discussion internes actifs", score: 1 },
        { id: "1.5", label: "Outils de chat/messagerie instantanée", score: 2 },
        { id: "1.6", label: "Communautés de pratique (CoP) formellement organisées", score: 2 },
        { id: "1.7", label: "Points de partage de connaissances en réunion d'équipe", score: 1 },
      ],
    },
    {
      id: "collaboratif",
      label: "Espace collaboratif et projets",
      radarLabel: "Collaboratif",
      color: "#f97316",
      items: [
        { id: "2.1", label: "Projets formalisés de transfert de savoir-faire", score: 2 },
        { id: "2.2", label: "Espace de travail collaboratif partagé (SharePoint, Teams)", score: 2 },
        { id: "2.3", label: "Capitalisation des connaissances en fin de projet", score: 2 },
        { id: "2.4", label: "Calendrier partagé des expertises disponibles", score: 2 },
        { id: "2.5", label: "Binômes expert/novice lors des projets", score: 2 },
        { id: "2.6", label: "Livrables systématiquement archivés et accessibles", score: 3 },
      ],
    },
    {
      id: "veille",
      label: "Intelligence économique et veille",
      radarLabel: "Veille",
      color: "#eab308",
      items: [
        { id: "3.1", label: "Processus de veille technologique/réglementaire/concurrentielle", score: 1 },
        { id: "3.2", label: "Accès aux bases de données et ressources documentaires externes", score: 1 },
        { id: "3.3", label: "Diffusion formalisée des informations de veille", score: 2 },
        { id: "3.4", label: "Responsable de la veille ou réseau de veilleurs désigné", score: 2 },
        { id: "3.5", label: "Participation encouragée aux événements externes (congrès, salons)", score: 1 },
        { id: "3.6", label: "Formalisation et partage des retours d'expériences externes", score: 1 },
      ],
    },
    {
      id: "documentation",
      label: "Production et gestion documentaire",
      radarLabel: "Documentation",
      color: "#84cc16",
      items: [
        { id: "4.1", label: "Formalisation systématique des actions et décisions importantes", score: 2 },
        { id: "4.2", label: "Système de gestion documentaire (GED) structuré et à jour", score: 3 },
        { id: "4.3", label: "Documents classifiés, versionnés et accessibles aux concernés", score: 2 },
        { id: "4.4", label: "Procédures, modes opératoires et instructions rédigés/maintenus", score: 2 },
        { id: "4.5", label: "Retours d'expérience (REX) documentés de façon structurée", score: 2 },
        { id: "4.6", label: "Cycle de vie des documents géré (création, révision, archivage)", score: 2 },
        { id: "4.7", label: "Accès aux documents maîtrisés selon les profils utilisateurs", score: 2 },
      ],
    },
    {
      id: "learning",
      label: "Apprentissage et tutorat",
      radarLabel: "Apprentissage",
      color: "#10b981",
      items: [
        { id: "5.1", label: "Actions de tutorat ou mentorat pour la transmission des savoirs", score: 2 },
        { id: "5.2", label: "Plan de formation annuel intégrant la gestion des connaissances", score: 2 },
        { id: "5.3", label: "Guides, manuels ou bases de connaissances internes (wiki)", score: 2 },
        { id: "5.4", label: "Capitalisation des formations internes (supports, enregistrements)", score: 2 },
        { id: "5.5", label: "Dispositif d'intégration structuré (onboarding) pour les nouveaux", score: 1 },
        { id: "5.6", label: "Parcours de montée en compétences formalisés par métier/poste", score: 2 },
        { id: "5.7", label: "Capture des savoirs tacites des experts avant leur départ", score: 2 },
      ],
    },
    {
      id: "expertise",
      label: "Cartographie de l'expertise",
      radarLabel: "Expertise",
      color: "#14b8a6",
      items: [
        { id: "6.1", label: "Experts par domaine formellement identifiés et référencés", score: 2 },
        { id: "6.2", label: "Annuaire des expertises internes disponible et à jour", score: 1 },
        { id: "6.3", label: "Niveaux d'expertise (novice, confirmé, expert) évalués", score: 2 },
        { id: "6.4", label: "Réseau d'experts transverse (communautés, clubs) organisé", score: 1 },
        { id: "6.5", label: "Cartographie des expertises liée au plan de succession (GPEC)", score: 2 },
        { id: "6.6", label: "Risques de perte de connaissances critiques (départs) identifiés", score: 1 },
        { id: "6.7", label: "Processus de reconnaissance et valorisation des experts", score: 2 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et gouvernance KM",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe projet KM (Knowledge Manager, RH, DSI, métiers)",
        "Réaliser le diagnostic de maturité KM sur les 6 dimensions",
        "Identifier les axes prioritaires et les risques de perte de savoirs",
        "Obtenir l'engagement de la direction et définir la gouvernance KM",
        "Élaborer la feuille de route KM avec objectifs et indicateurs",
      ],
      milestone: "Rapport de maturité KM approuvé, gouvernance et feuille de route validées",
    },
    {
      phase: 2,
      title: "Phase 2 — Documentation et GED",
      duration: "3 mois",
      actions: [
        "Déployer ou renforcer le système de gestion documentaire (GED)",
        "Structurer la taxonomie documentaire et les règles de classement",
        "Formaliser les procédures, modes opératoires et instructions critiques",
        "Mettre en place le processus de capitalisation REX (retours d'expérience)",
        "Former les collaborateurs à l'utilisation de la GED",
      ],
      milestone: "GED opérationnelle, base documentaire structurée, processus REX actif",
    },
    {
      phase: 3,
      title: "Phase 3 — Communautés de pratique et tutorat",
      duration: "4 mois",
      actions: [
        "Créer et animer les premières communautés de pratique (CoP) par domaine",
        "Déployer un programme de tutorat/mentorat pour les transferts de savoirs",
        "Mettre en place un espace collaboratif (SharePoint, Teams, wiki interne)",
        "Structurer le plan de formation intégrant les objectifs KM",
        "Lancer les sessions régulières de partage d'expériences inter-équipes",
      ],
      milestone: "CoP actives, programme tutorat lancé, espace collaboratif déployé",
    },
    {
      phase: 4,
      title: "Phase 4 — Cartographie des expertises et succession",
      duration: "3 mois",
      actions: [
        "Réaliser la cartographie complète des expertises et compétences clés",
        "Identifier les savoirs critiques à risque (départs, retraites, postes clés)",
        "Construire les plans de succession et parcours de montée en compétences",
        "Déployer le processus de veille et d'intelligence économique",
        "Mettre en place les indicateurs de performance KM (tableau de bord)",
      ],
      milestone: "Cartographie expertises finalisée, plans succession validés, KPI KM actifs",
    },
    {
      phase: 5,
      title: "Phase 5 — Ancrage culturel et amélioration continue",
      duration: "Continu",
      actions: [
        "Intégrer la culture KM dans les rituels managériaux et évaluations RH",
        "Mesurer annuellement la maturité KM et actualiser la feuille de route",
        "Étendre la démarche KM aux filiales et partenaires stratégiques",
        "Reconnaître et valoriser les contributions au partage des connaissances",
      ],
      milestone: "Culture KM ancrée, maturité globale ≥ 3/4, programme de reconnaissance actif",
    },
  ],
}
