import type { FrameworkConfig } from "./types"

export const smqhseConfig: FrameworkConfig = {
  id: "smqhse",
  name: "SMQHSE — ISO 9001 / ISO 14001 / ISO 45001",
  shortName: "SMQHSE",
  description: "Système de management intégré Qualité, Sécurité et Environnement — Triple certification ISO HLS",
  iconName: "ShieldCheck",
  accentColor: "blue",
  maxScore: 5,
  globalScoreMock: 1.93,
  dimensions: [
    {
      id: "ch4",
      label: "Contexte de l'organisme",
      radarLabel: "Contexte",
      color: "#3b82f6",
      items: [
        { id: "4.1", label: "Comprendre l'organisme et son contexte (enjeux internes/externes)", score: 2 },
        { id: "4.2", label: "Comprendre les besoins et attentes des parties intéressées", score: 2 },
        { id: "4.3", label: "Définir le domaine d'application du SMQHSE (sites, produits, services)", score: 1 },
        { id: "4.4", label: "Établir et maintenir le système de management et ses processus", score: 1 },
      ],
    },
    {
      id: "ch5",
      label: "Leadership",
      radarLabel: "Leadership",
      color: "#6366f1",
      items: [
        { id: "5.1", label: "Leadership et engagement de la direction générale envers le SMQHSE", score: 2 },
        { id: "5.2", label: "Politique QHSE — contenu, conformité, prévention, amélioration continue", score: 2 },
        { id: "5.3", label: "Rôles, responsabilités et autorités QHSE (y compris terrain et sous-traitants)", score: 2 },
        { id: "5.4", label: "Consultation et participation des travailleurs (comités sécu, remontées terrain)", score: 1 },
      ],
    },
    {
      id: "ch6",
      label: "Planification",
      radarLabel: "Planification",
      color: "#8b5cf6",
      items: [
        { id: "6.1", label: "Planifier les actions face aux risques et opportunités QHSE", score: 2 },
        { id: "6.1.2", label: "Identification des dangers et évaluation des risques SST (JSA, PTW, LOTO)", score: 2 },
        { id: "6.1.3", label: "Obligations de conformité — registre légal, permis, rejets, déchets", score: 1 },
        { id: "6.2", label: "Objectifs QHSE et KPI (TRIR/LTI, spills, NC, OTIF, réclamations)", score: 2 },
        { id: "6.3", label: "Gestion du changement (MOC) — modifications procédé, équipements, organisation", score: 2 },
      ],
    },
    {
      id: "ch7",
      label: "Support",
      radarLabel: "Support",
      color: "#a855f7",
      items: [
        { id: "7.1", label: "Ressources humaines, équipements, budgets, EPI, maintenance critique", score: 2 },
        { id: "7.2", label: "Compétences et habilitations — formation HSE (PTW, H2S, incendie, CACES)", score: 2 },
        { id: "7.3", label: "Sensibilisation — culture sécurité, règles vitales, Stop Work Authority", score: 2 },
        { id: "7.4", label: "Communication — reporting QHSE, gestion de crise, remontée incidents", score: 1 },
        { id: "7.5", label: "Information documentée — procédures, modes opératoires, versions, enregistrements", score: 2 },
      ],
    },
    {
      id: "ch8",
      label: "Réalisation opérationnelle",
      radarLabel: "Réalisation",
      color: "#ec4899",
      items: [
        { id: "8.1", label: "Planification et maîtrise opérationnelle — procédés, sous-traitants, inspections", score: 2 },
        { id: "8.1.2", label: "Préparation et réponse urgences majeures (incendie, fuite, spill, évacuation)", score: 2 },
        { id: "8.1.3", label: "Gestion achats/contractants — exigences QHSE, évaluation, induction, supervision", score: 2 },
        { id: "8.2", label: "Qualité produit/service — maîtrise exigences client, contrôles, NC, traçabilité", score: 2 },
        { id: "8.4", label: "Maîtrise des prestations externes — fournisseurs critiques, réception, performance", score: 2 },
        { id: "8.6", label: "Libération des produits et services — critères, preuves, autorisation", score: 2 },
        { id: "8.7", label: "Maîtrise des éléments de sortie non conformes — retrait, traitement, documentation", score: 1 },
      ],
    },
    {
      id: "ch9",
      label: "Évaluation des performances",
      radarLabel: "Évaluation",
      color: "#f97316",
      items: [
        { id: "9.1", label: "Surveillance et mesure — inspections terrain, monitoring rejets, audits conformité", score: 2 },
        { id: "9.1.2", label: "Évaluation de la conformité — contrôles réglementaires, reporting autorités", score: 2 },
        { id: "9.2", label: "Audit interne QHSE — programme basé risques, audits sites et sous-traitants", score: 1 },
        { id: "9.3", label: "Revue de direction — performance QHSE, incidents majeurs, objectifs, ressources", score: 2 },
      ],
    },
    {
      id: "ch10",
      label: "Amélioration",
      radarLabel: "Amélioration",
      color: "#10b981",
      items: [
        { id: "10.1", label: "Amélioration continue — initiatives, standardisation, leçons apprises, digitalisation", score: 2 },
        { id: "10.2", label: "Incidents/NC et actions correctives — RCA (5 Why, arbre causes), CAPA, efficacité", score: 2 },
        { id: "10.3", label: "Amélioration env. et SST — réduction émissions/spills, programmes comportementaux", score: 2 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et engagement",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe projet SMQHSE (pilote, responsables Q/S/E)",
        "Réaliser le diagnostic de maturité par clause HLS",
        "Identifier les 10 clauses prioritaires (score ≤ 1)",
        "Obtenir l'engagement formel de la direction",
        "Définir le périmètre et la portée du SMI",
      ],
      milestone: "Rapport de diagnostic validé, lettre d'engagement direction",
    },
    {
      phase: 2,
      title: "Phase 2 — Politique et planification",
      duration: "3 mois",
      actions: [
        "Rédiger et diffuser la politique QHSE intégrée",
        "Cartographier les processus et leurs interactions",
        "Établir le registre des risques QHSE et la cartographie des dangers SST",
        "Mettre en place le registre des exigences légales et réglementaires",
        "Définir les objectifs QHSE avec KPI et tableau de bord",
      ],
      milestone: "Politique QHSE publiée, registre légal opérationnel, objectifs définis",
    },
    {
      phase: 3,
      title: "Phase 3 — Déploiement opérationnel",
      duration: "5 mois",
      actions: [
        "Rédiger les procédures et instructions de travail critiques",
        "Former l'ensemble du personnel aux exigences QHSE",
        "Déployer les PRP et contrôles opérationnels (PTW, LOTO, inspections)",
        "Mettre en place la gestion documentaire (GED)",
        "Déployer la maîtrise des non-conformités et le système CAPA",
      ],
      milestone: "Procédures opérationnelles en place, personnel formé, GED active",
    },
    {
      phase: 4,
      title: "Phase 4 — Évaluation et audit interne",
      duration: "3 mois",
      actions: [
        "Réaliser le premier audit interne SMQHSE complet",
        "Analyser les KPI et indicateurs de performance",
        "Conduire la revue de direction",
        "Traiter les écarts et mettre à jour le plan d'actions",
        "Réaliser un audit blanc pré-certification",
      ],
      milestone: "Rapport d'audit interne, revue de direction documentée, plan CAPA à jour",
    },
    {
      phase: 5,
      title: "Phase 5 — Certification triple ISO",
      duration: "3 mois",
      actions: [
        "Préparer et soumettre le dossier à l'organisme certificateur",
        "Accompagner l'audit de certification Étape 1 (revue documentaire)",
        "Accompagner l'audit de certification Étape 2 (audit terrain)",
        "Traiter les écarts identifiés lors de la certification",
        "Obtenir les certificats ISO 9001 / 14001 / 45001",
      ],
      milestone: "Certificats ISO 9001:2015 + ISO 14001:2015 + ISO 45001:2018 obtenus",
    },
  ],
}
