import type { FrameworkConfig } from "./types"

export const smsiConfig: FrameworkConfig = {
  id: "smsi",
  name: "SMSI — ISO/IEC 27001:2022",
  shortName: "ISO 27001",
  description: "Système de Management de la Sécurité de l'Information — Certification ISO/IEC 27001:2022",
  iconName: "ShieldAlert",
  accentColor: "violet",
  maxScore: 5,
  globalScoreMock: 2.03,
  dimensions: [
    {
      id: "hls",
      label: "Chapitres HLS 4-10",
      radarLabel: "HLS (4-10)",
      color: "#7c3aed",
      items: [
        { id: "hls.4", label: "Ch.4 Contexte — enjeux, parties intéressées, périmètre SMSI", score: 2 },
        { id: "hls.5", label: "Ch.5 Leadership — engagement direction, politique SSI, rôles", score: 2 },
        { id: "hls.6", label: "Ch.6 Planification — risques SI, traitement, DdA (Déclaration d'Applicabilité)", score: 2 },
        { id: "hls.7", label: "Ch.7 Support — ressources, compétences, sensibilisation, communication, docs", score: 2 },
        { id: "hls.8", label: "Ch.8 Réalisation — mise en œuvre du plan de traitement des risques SI", score: 2 },
        { id: "hls.9", label: "Ch.9 Évaluation — surveillance, audit interne SMSI, revue de direction", score: 2 },
        { id: "hls.10", label: "Ch.10 Amélioration — non-conformités, CAPA, amélioration continue SMSI", score: 1 },
      ],
    },
    {
      id: "a5",
      label: "Mesures organisationnelles (A.5)",
      radarLabel: "Org. (A.5)",
      color: "#8b5cf6",
      items: [
        { id: "a5.1",  label: "A.5.1 Politiques de sécurité de l'information", score: 2 },
        { id: "a5.2",  label: "A.5.2 Rôles et responsabilités en sécurité de l'information", score: 2 },
        { id: "a5.9",  label: "A.5.9 Inventaire des actifs informationnels", score: 2 },
        { id: "a5.10", label: "A.5.10 Utilisation autorisée des actifs", score: 2 },
        { id: "a5.15", label: "A.5.15 Contrôle d'accès — politique et gestion des droits", score: 2 },
        { id: "a5.17", label: "A.5.17 Informations d'authentification — politique et gestion", score: 2 },
        { id: "a5.19", label: "A.5.19 Sécurité de l'information dans les relations fournisseurs", score: 2 },
        { id: "a5.23", label: "A.5.23 Sécurité pour l'utilisation des services cloud", score: 2 },
        { id: "a5.24", label: "A.5.24 Planification de la gestion des incidents SI", score: 2 },
        { id: "a5.27", label: "A.5.27 Apprentissage tiré des incidents de sécurité", score: 2 },
        { id: "a5.30", label: "A.5.30 Préparation aux TIC pour la continuité d'activité", score: 2 },
        { id: "a5.37", label: "A.5.37 Procédures d'exploitation documentées", score: 2 },
      ],
    },
    {
      id: "a6",
      label: "Mesures liées aux personnes (A.6)",
      radarLabel: "Personnel (A.6)",
      color: "#a855f7",
      items: [
        { id: "a6.1", label: "A.6.1 Présélection (vérification des antécédents)", score: 2 },
        { id: "a6.2", label: "A.6.2 Conditions d'emploi — clauses SI dans les contrats", score: 2 },
        { id: "a6.3", label: "A.6.3 Sensibilisation, formation et éducation SI", score: 2 },
        { id: "a6.4", label: "A.6.4 Processus disciplinaire en cas de violation SI", score: 2 },
        { id: "a6.5", label: "A.6.5 Responsabilités après cessation ou changement de poste", score: 2 },
        { id: "a6.6", label: "A.6.6 Accords de confidentialité et de non-divulgation", score: 2 },
        { id: "a6.7", label: "A.6.7 Travail à distance — règles de sécurité et contrôles", score: 2 },
        { id: "a6.8", label: "A.6.8 Signalement des événements liés à la sécurité de l'info", score: 2 },
      ],
    },
    {
      id: "a7",
      label: "Mesures physiques (A.7)",
      radarLabel: "Physique (A.7)",
      color: "#6366f1",
      items: [
        { id: "a7.1",  label: "A.7.1 Périmètres de sécurité physique (zones sécurisées)", score: 3 },
        { id: "a7.2",  label: "A.7.2 Contrôle des accès physiques aux zones sécurisées", score: 2 },
        { id: "a7.3",  label: "A.7.3 Sécurisation des bureaux, salles et installations", score: 2 },
        { id: "a7.4",  label: "A.7.4 Surveillance physique (CCTV, alarme, rondes)", score: 2 },
        { id: "a7.5",  label: "A.7.5 Protection contre les menaces physiques et environnementales", score: 2 },
        { id: "a7.8",  label: "A.7.8 Emplacement et protection du matériel informatique", score: 2 },
        { id: "a7.10", label: "A.7.10 Supports de stockage — gestion, mise au rebut sécurisée", score: 2 },
        { id: "a7.14", label: "A.7.14 Mise au rebut ou réutilisation sécurisée des équipements", score: 2 },
      ],
    },
    {
      id: "a8",
      label: "Mesures technologiques (A.8)",
      radarLabel: "Tech. (A.8)",
      color: "#818cf8",
      items: [
        { id: "a8.2",  label: "A.8.2 Droits d'accès privilégiés — gestion et surveillance", score: 2 },
        { id: "a8.5",  label: "A.8.5 Authentification sécurisée (MFA, SSO, politiques MDP)", score: 2 },
        { id: "a8.7",  label: "A.8.7 Protection contre les logiciels malveillants (antivirus, EDR)", score: 2 },
        { id: "a8.8",  label: "A.8.8 Gestion des vulnérabilités techniques (scan, patch management)", score: 2 },
        { id: "a8.12", label: "A.8.12 Prévention des fuites de données (DLP)", score: 2 },
        { id: "a8.15", label: "A.8.15 Journalisation et surveillance des événements SI", score: 2 },
        { id: "a8.16", label: "A.8.16 Activités de surveillance — SIEM, détection d'anomalies", score: 2 },
        { id: "a8.20", label: "A.8.20 Sécurité des réseaux (segmentation, pare-feu, IDS/IPS)", score: 2 },
        { id: "a8.23", label: "A.8.23 Filtrage web et contrôle des flux sortants", score: 2 },
        { id: "a8.24", label: "A.8.24 Utilisation de la cryptographie (chiffrement, PKI)", score: 2 },
        { id: "a8.28", label: "A.8.28 Codage sécurisé (SSDLC, revue de code, tests sécurité)", score: 1 },
        { id: "a8.34", label: "A.8.34 Protection des systèmes d'information lors des audits", score: 1 },
      ],
    },
  ],
  roadmap: [
    {
      phase: 1,
      title: "Phase 1 — Diagnostic et périmètre SMSI",
      duration: "2 mois",
      actions: [
        "Constituer l'équipe projet SMSI (RSSI, responsables SI, DPO)",
        "Réaliser le diagnostic de maturité par clause HLS et Annexe A",
        "Définir le périmètre du SMSI (sites, systèmes, services, actifs)",
        "Identifier les parties intéressées et leurs exigences SI",
        "Obtenir l'engagement formel de la direction générale",
      ],
      milestone: "Rapport de diagnostic validé, périmètre SMSI approuvé par la direction",
    },
    {
      phase: 2,
      title: "Phase 2 — Politique, appréciation des risques et DdA",
      duration: "4 mois",
      actions: [
        "Rédiger et diffuser la politique de sécurité de l'information",
        "Réaliser l'inventaire des actifs et la classification des informations",
        "Conduire l'appréciation des risques SI (identification, analyse, évaluation)",
        "Définir le plan de traitement des risques et le RACI",
        "Rédiger la Déclaration d'Applicabilité (DdA) avec justifications",
      ],
      milestone: "Politique SSI publiée, DdA finalisée, plan de traitement des risques approuvé",
    },
    {
      phase: 3,
      title: "Phase 3 — Déploiement des contrôles Annexe A",
      duration: "6 mois",
      actions: [
        "Mettre en œuvre les mesures organisationnelles prioritaires (A.5)",
        "Déployer les contrôles techniques (A.8) : MFA, DLP, SIEM, patch mgmt",
        "Renforcer la sécurité physique et les accès (A.7)",
        "Former et sensibiliser tous les collaborateurs à la sécurité SI",
        "Mettre en place la gestion des incidents et la procédure de signalement",
      ],
      milestone: "Contrôles Annexe A déployés, personnel formé, procédures opérationnelles actives",
    },
    {
      phase: 4,
      title: "Phase 4 — Audit interne et revue de direction",
      duration: "3 mois",
      actions: [
        "Réaliser le premier audit interne SMSI complet (tous les chapitres HLS)",
        "Analyser les indicateurs de performance sécurité (KRI, incidents, vulnérabilités)",
        "Conduire la revue de direction SMSI (résultats, ressources, objectifs)",
        "Traiter les non-conformités et mettre à jour le plan d'actions CAPA",
        "Réaliser un audit blanc pré-certification avec un consultant externe",
      ],
      milestone: "Rapport d'audit interne, revue de direction documentée, plan CAPA finalisé",
    },
    {
      phase: 5,
      title: "Phase 5 — Certification ISO/IEC 27001:2022",
      duration: "3 mois",
      actions: [
        "Préparer le dossier de certification (DdA, politique, registre des risques)",
        "Accompagner l'audit de Stage 1 (revue documentaire par l'OC)",
        "Accompagner l'audit de Stage 2 (audit terrain complet)",
        "Traiter les écarts et non-conformités relevés par l'auditeur",
        "Obtenir le certificat ISO/IEC 27001:2022 et planifier la surveillance",
      ],
      milestone: "Certificat ISO/IEC 27001:2022 obtenu, plan de surveillance triennale établi",
    },
  ],
}
